# Some randomizer settings for monsters

# Config version
Config-Version: 1

# Names
1: "BillyBobJones"
2: "Ethreal"
3: "Nekros"
4: "Calamity"
5: "Yondra"
6: "Skell"
7: "Gorge"
8: "Hellion"
9: "Cursed"
10: "?"

# Name lists (Must be changed if the name section is)
MonsterNames:
- BillyBobJones
- Ethreal
- Nekros
- Calamity
- Yondra
- Skell
- Gorge
- Hellion
- Cursed
- ?

# Abilities (On damage)
11: "FlameAttack"
12: "DoubleDamage"